; ---------------- GPU MEMORY USED ----------------

[MeasureGPUMemUsedRaw]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw4

; ---------------- GPU MEMORY TOTAL ----------------
[Variables]
color=255, 255, 255, 220
color2=255, 255, 255, 200
graph.line=255, 0, 0, 255
graph.line2=255, 255, 255, 50
font=Plantagenet Cherokee
GPUMemoryTotal=8192


; ---------- Transform to percentage

[MeasureGPUMemPercent]
Measure=Calc
Formula=(MeasureGPUMemUsedRaw / #GPUMemoryTotal#) * 100
MinValue=0
MaxValue=100
DynamicVariables=1

; ---------- Graphs

[GPUMemGraph1]
Meter=Line
MeasureName=MeasureGPUMemPercent
X=0
Y=70
H=30
W=100
LineCount=1
LineColor=#graph.line#
AntiAlias=1
MinValue=0
MaxValue=100

[GPUMemGraph2]
Meter=HISTOGRAM
MeasureName=MeasureGPUMemPercent
X=r
Y=r
H=29
W=100
PrimaryColor=#graph.line2#
AntiAlias=1
MinValue=0
MaxValue=100

; ------------ Vertical Bar

[MonitorGPUMemBackground]
Meter=IMAGE
SolidColor=#graph.line2#
X=142
Y=60
W=5
H=55

[MonitorGPUMemBar]
Meter=BAR
MeasureName=MeasureGPUMemPercent
X=r
Y=r
W=5
H=55
BarColor=#graph.line#
BarOrientation=VERTICAL
MinValue=0
MaxValue=100

; -------------Text Display

[vRAM]
Meter=STRING
MeasureName=MeasureUsedRAM
X=174
Y=76
FontColor=#color#
FontFace=#Font#
FontSize=11
StringAlign=Center
StringStyle=BOLD
AntiAlias=1
Text="vRAM"
Percentual=1

[GPUMemPercentText]
Meter=STRING
MeasureName=MeasureGPUMemPercent
X=121
Y=82
FontColor=#color#
FontFace=#Font#
FontSize=11
StringAlign=Center
StringStyle=BOLD
AntiAlias=1
Text="%1%"
Percentual=1

[GPUMemUsedText]
Meter=STRING
MeasureName=MeasureGPUMemUsedRaw
X=174
Y=95
StringAlign=Center
FontColor=#color#
FontSize=7
FontFace=#Font#
StringStyle=Bold
AntiAlias=1
AutoScale=1
NumOfDecimals=1
PostFix=" MB"

[UsedOverTotalvRAM]
Meter=STRING
X=169
Y=104
FontColor=#color#
FontFace=#Font#
FontSize=7
StringAlign=RIGHT
StringStyle=BOLD
Text="of"
AntiAlias=1

[GPUMemTotalText]
Meter=STRING
X=169
Y=104
FontColor=#color#
FontSize=7
FontFace=#Font#
StringAlign=Left
StringStyle=Bold
AntiAlias=1
Text="#GPUMemoryTotal# MB"

